sudo: required
services:
  - docker

before_install:
  - docker build -t sandjaie/fib-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sandjaie/fib-client-test npm run test -- --coverage

after_success:
  - docker build -t sandjaie/fib-client ./client
  - docker build -t sandjaie/fib-server ./server
  - docker build -t sandjaie/fib-worker ./worker
  - docker build -t sandjaie/fib-nginx ./nginx
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker tag sandjaie/fib-client sandjaie/fib-client:$TRAVIS_BUILD_NUMBER
  - docker push sandjaie/fib-client

  - docker tag sandjaie/fib-worker sandjaie/fib-worker:$TRAVIS_BUILD_NUMBER
  - docker push sandjaie/fib-worker

  - docker tag sandjaie/fib-server sandjaie/fib-server:$TRAVIS_BUILD_NUMBER
  - docker push sandjaie/fib-server

  - docker tag sandjaie/fib-nginx sandjaie/fib-nginx:$TRAVIS_BUILD_NUMBER
  - docker push sandjaie/fib-nginx