sudo: required
services:
  - docker

before_install:
  - docker build -t sandjaie/fib-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sandjaie/fib-client-test npm run test -- --coverage

after_success:
  - docker build -t sandjaie/fib-client ./client
  - docker build -t sandjaie/fib-server ./server
  - docker build -t sandjaie/fib-worker ./worker
  - docker build -t sandjaie/fib-nginx ./nginx
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sandjaie/fib-client:$TRAVIS_JOB_ID
  - docker tag sandjaie/fib-client:$TRAVIS_JOB_ID sandjaie/fib-client:latest
  - docker push sandjaie/fib-server:$TRAVIS_JOB_ID
  - docker tag sandjaie/fib-server:$TRAVIS_JOB_ID sandjaie/fib-server:latest
  - docker push sandjaie/fib-worker:$TRAVIS_JOB_ID
  - docker tag sandjaie/fib-worker:$TRAVIS_JOB_ID sandjaie/fib-worker:latest
  - docker push sandjaie/fib-nginx:$TRAVIS_JOB_ID
  - docker tag sandjaie/fib-nginx:$TRAVIS_JOB_ID sandjaie/fib-nginx:latest